services:
  postgres:
    image: postgres:17
    container_name: postgres17-techblog
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techblog
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d techblog"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
